### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'NoneType' 

### ISSUE THREAD

**Issue by c5shen** [vlasmirnov/GCM#7]
Python version: 3.7.0
Java version: 1.8

When running tasks for 16S.M dataset pulled from https://crw-site.chemistry.gatech.edu/DAT/3C/Alignment/Files/16S/16S.M.alnfasta.zip (unaligned sequences pulled from the alignment file), the following error occurred after getting the info `Using 10 MAFFT backbones...`:
```bash
Traceback (most recent call last):
  File "/home/chengze5/scratch/softwares/MAGUS/magus.py", line 24, in main
    mainAlignmentTask()
  File "/scratch/users/chengze5/softwares/MAGUS/align/aligner.py", line 25, in mainAlignmentTask
    task.awaitTask()
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/task.py", line 39, in awaitTask
    awaitTasks([self])
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/task.py", line 82, in awaitTasks
    controller.awaitTasks(tasks)
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/controller.py", line 29, in awaitTasks
    observeTaskManager()
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/controller.py", line 48, in observeTaskManager
    runTask(task)
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/manager.py", line 204, in runTask
    task.run()
  File "/scratch/users/chengze5/softwares/MAGUS/tasks/task.py", line 47, in run
    func(**self.taskArgs)
  File "/scratch/users/chengze5/softwares/MAGUS/align/aligner.py", line 43, in runAlignmentTask
    mergeSubalignments(context)
  File "/scratch/users/chengze5/softwares/MAGUS/align/merge/merger.py", line 22, in mergeSubalignmen
    buildGraph(context)
  File "/scratch/users/chengze5/softwares/MAGUS/align/merge/graph_build/graph_builder.py", line 29,
    context.graph.initializeMatrix()
  File "/scratch/users/chengze5/softwares/MAGUS/align/merge/alignment_graph.py", line 45, in initial
    self.matrixSize = sum(self.subalignmentLengths)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

Before that, I noticed all the subsets contain 0/200 sequences so MAFFT was basically aligning empty files. Maybe it is an issue with how sequences are read in from the file?

**Comment by c5shen** [comment]
Eliminated by removing all colons from the taxa names.
